name = "speedtest-pwsh"
main = "worker/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[routes]]
pattern = "speed.it2.sh/*"
custom_domain = true
